_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 41
                - 55
                - 79
            "2":
                - 1
                - 41
                - 55
                - 79
            "3":
                - 23
                - 55
            "4": 3.10.0
            "5": 0.19.4
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
