name: coral
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - gdal=3.11.0
  - pip:
      - affine==2.4.0
      - annotated-types==0.7.0
      - anyio==4.8.0
      - argon2-cffi==23.1.0
      - arrow==1.3.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cligj==0.7.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - decorator==5.1.1
      - docker-pycreds==0.4.0
      - fastjsonschema==2.21.1
      - fonttools==4.55.4
      - fsspec==2024.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - httpx==0.28.1
      - ipykernel==6.29.5
      - ipython==8.31.0
      - ipywidgets==8.1.5
      - jedi==0.19.2
      - jinja2==3.1.3
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jupyter==1.1.1
      - jupyterlab==4.3.4
      - kornia==0.8.0
      - kornia-rs==0.1.8
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.7
      - nbconvert==7.16.5
      - nbformat==5.10.4
      - networkx==3.2.1
      - notebook==7.3.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cuda-runtime-cu12==12.1.105
      - pillow==10.2.0
      - protobuf==5.29.3
      - psutil==6.1.1
      - pycparser==2.22
      - pydantic==2.10.5
      - pygments==2.19.1
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - rasterio==1.4.3
      - requests==2.32.3
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - sentry-sdk==2.20.0
      - setproctitle==1.3.4
      - six==1.17.0
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - tomli==2.2.1
      - torch==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.1.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - wandb==0.19.4
